### PR TITLE
fix: address errors raised rewites(mapping 58)

### LINKED ISSUE #1067: Retry Strategy: Rewrites should only retry when IfGenerationMatch is provided
Tracking bug to retry rewrites only when IfGenerationMatch is provided.

### PR DESCRIPTION
**Pull request by frankyn**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

Fixes #1067☕️

### CODE REVIEW

File: google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java [hunk 1]
```diff
@@ -1839,15 +1840,39 @@ private static void compose(ArrayList<RpcMethodMapping> a) {
       private static void rewrite(ArrayList<RpcMethodMapping> a) {
         a.add(
             RpcMethodMapping.newBuilder(58, objects.rewrite)
+                // Question: Retries occurred when they shouldn't have but withApplicable disabled
+                // this case. Is there an alternate for negative case?
```
Comment (BenWhitehead) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java:1844]: I don't think we need this comment any more, correct?

```suggestion
```

File: google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java [hunk 2]
```diff
@@ -1839,15 +1840,39 @@ private static void compose(ArrayList<RpcMethodMapping> a) {
...
+                                          BlobId.of(c.getBucketName(), "destination-blob"),
+                                          BlobTargetOption.doesNotExist())
+                                      .build();
+                              return state.with(ctx.getStorage().copy(copyRequest));
+                            }))
+                .build());
+        a.add(
+            RpcMethodMapping.newBuilder(242, objects.rewrite)
+                // Question: Retries occurred when they shouldn't have but withApplicable disabled
+                // this case. Is there an alternate for negative case?
```
Comment (BenWhitehead) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java:1863]: I don't think we need this comment any more, correct?

```suggestion
```

**Review by BenWhitehead — APPROVED** [review]
Couple minor questions, other than that LGTM.
