### PR TITLE
fix: Documentation for Blob.update() and Storage.update() methods is confusing/incorrect

### LINKED ISSUE #252: Documentation for Blob.update() and Storage.update() methods is confusing/incorrect.
Documentation for Blob.update(Options...) doesn't include example of usage, the provided examples demonstrate how to use `Storage.update(blobInfo)`. The doc also mentions non existing parameter `blobInfo`: `Original metadata are merged with metadata in the provided blobInfo. `
Taking into account the fact that `Objects of this class are immutable.` this method seems useless. 
The documentation should be updated to clarify usage.

Documentation for Storage.update() methods is better but still confusing. The important aspects are not covered:
- The term `metadata` could be read as `blob's information` or as `blob's user provided metadata`
- It's not clarify if blob's generation is updated
- What happens if  the preconditions specified by the options fail

Documentation should be aligned with the new Blob/BlobInfo API Doc introduced by https://github.com/googleapis/java-storage/issues/176

### PR DESCRIPTION
**Pull request by dmitry-fa**
Fixes #252

### CODE REVIEW

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java [hunk 1]
```diff
@@ -546,44 +546,24 @@ public Blob reload(BlobSourceOption... options) {
   }
 
   /**
-   * Updates the blob's information. Bucket or blob's name cannot be changed by this method. If you
-   * want to rename the blob or move it to a different bucket use the {@link #copyTo} and {@link
-   * #delete} operations. A new {@code Blob} object is returned. By default no checks are made on
-   * the metadata generation of the current blob. If you want to update the information only if the
-   * current blob metadata are at their latest version use the {@code metagenerationMatch} option:
-   * {@code newBlob.update(BlobTargetOption.metagenerationMatch())}.
+   * Updates the blob properties. Optional {@code options} parameter can contain the preconditions
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:549]: Optional --> The
can contain the --> contains

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java [hunk 2]
```diff
@@ -546,44 +546,24 @@ public Blob reload(BlobSourceOption... options) {
...
+   * for applying the update. To update the properties you need to call {@link #toBuilder()}, set
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:550]: delete "you need to"

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java [hunk 3]
```diff
@@ -546,44 +546,24 @@ public Blob reload(BlobSourceOption... options) {
...
+   * the properties you want to change, build the new {@code Blob} instance and then call {@link
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:551]: instance,

Comment (dmitry-fa) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java]: Thanks!

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java [hunk 4]
```diff
@@ -546,44 +546,24 @@ public Blob reload(BlobSourceOption... options) {
...
-   *     .build());
+   * BlobId blobId = BlobId.of(bucketName, blobName);
+   * Blob blob = storage.get(blobId);
+   * blob.toBuilder().setContentType("text/plain").build().update();
    * }</pre>
    *
-   * @param options update options
-   * @return a {@code Blob} object with updated information
+   * @param options preconditions to apply the update
+   * @return the updated blob
```
Comment (frankyn) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:566]: `the updated {@code Blob}`

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java [hunk 5]
```diff
@@ -546,44 +546,24 @@ public Blob reload(BlobSourceOption... options) {
   }
 
   /**
-   * Updates the blob's information. Bucket or blob's name cannot be changed by this method. If you
-   * want to rename the blob or move it to a different bucket use the {@link #copyTo} and {@link
-   * #delete} operations. A new {@code Blob} object is returned. By default no checks are made on
-   * the metadata generation of the current blob. If you want to update the information only if the
-   * current blob metadata are at their latest version use the {@code metagenerationMatch} option:
-   * {@code newBlob.update(BlobTargetOption.metagenerationMatch())}.
+   * Updates the blob properties. The {@code options} parameter contains the preconditions for
```
Comment (frankyn) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:549]: I'd state `{@code options}` is `BlobTargetOption` and instead of `preconditions` use `request options` and link to update API documentation: https://cloud.google.com/storage/docs/json_api/v1/objects/update

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java (hunk 4 above)
Comment (dmitry-fa) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java]: okay

File: google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java (hunk 5 above)
Comment (dmitry-fa) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:549]: > and link to update API documentation: https://cloud.google.com/storage/docs/json_api/v1/objects/update

done

> I'd state {@code options} is BlobTargetOption

I think this is clear from the parameter type

> and instead of preconditions use request options

Personally for me it was hard to understand the purspose of this parameter. So, I tried to rephrase this statement to help users not very familiar with the Storage details to get the meaning. I came up to:  `The options parameter contains the preconditions for  applying the update`

Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java:549]: Thanks, sgtm, I think having the link will help provide information.
