### PR TITLE
fix: KMS Bad Key error when using existing Blob context to overwrite object

### LINKED ISSUE #502: KMS Bad Key error when using existing Blob context to overwrite object.
A Bad Key error can occur when trying to overwrite an existing object when metadata with local metadata.

For example:
```
// Write an empty object with a kmsKeyName.
Blob blob = storage.create(blobInfo, Storage.BlobTargetOption.kmsKeyName(kmsKeyName))

// Using blob that already has metadata received from Storage API to create a writer.
WriteChannel writer = blob.writer();

// The following will error with the following error:
// {
//    "message": "Bad Cloud KMS crypto key: projects/project-id/locations/us/keyRings/lab1/cryptoKeys/annie-test-key/cryptoKeyVersions/1",
//    "domain": "global",
//     "reason": "invalid"
// }
writer.write(ByteBuffer.wrap(content, 0, content.length));
```

The recommended change is if kmsKeyName is defined in object metadata is to remove it the resource id contains:

```
/cryptoKeyVersions/..
````

### PR DESCRIPTION
**Pull request by athakor**
Fixes #502

### CODE REVIEW

**Review by frankyn — CHANGES_REQUESTED** [review]

File: google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java [hunk 1]
```diff
@@ -1095,8 +1095,10 @@ public ObjectAccessControl apply(Acl acl) {
     if (retentionExpirationTime != null) {
       storageObject.setRetentionExpirationTime(new DateTime(retentionExpirationTime));
     }
-
-    storageObject.setKmsKeyName(kmsKeyName);
+    storageObject.setKmsKeyName(
+        kmsKeyName != null && kmsKeyName.contains(cryptoKeyVersions)
+            ? kmsKeyName.substring(0, kmsKeyName.indexOf(cryptoKeyVersions))
```
[the remark this answers is not in the document]
Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java]: done

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 2]
```diff
@@ -832,6 +833,10 @@ public String open(StorageObject object, Map<Option, ?> options) {
     Span span = startSpan(HttpStorageRpcSpans.SPAN_NAME_OPEN);
     Scope scope = tracer.withSpan(span);
     try {
+      String kmsKey = object.getKmsKeyName();
+      if (kmsKey != null && kmsKey.contains(CRYPTO_KEY_VERSIONS)) {
+        object.setKmsKeyName(kmsKey.substring(0, kmsKey.indexOf(CRYPTO_KEY_VERSIONS)));
```
Comment (frankyn) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java:838]: Oh, instead unset the kms key. Additionally document this in BlobInfo setKmsKeyName java doc.

Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: done

Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: Whoops, I meant that you should update the metadata at this point to remove KmsKeyName if CryptoKeyVersion is supplied  *and* add documentation on this quirk.

Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: done

File: google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java [hunk 3]
```diff
@@ -625,7 +627,12 @@ Builder setCustomerEncryption(CustomerEncryption customerEncryption) {
 
     @Override
     Builder setKmsKeyName(String kmsKeyName) {
-      this.kmsKeyName = kmsKeyName;
+      String cryptoKeyVersions = "/cryptoKeyVersions/";
+      if (kmsKeyName != null && kmsKeyName.contains(cryptoKeyVersions)) {
+        this.kmsKeyName = kmsKeyName.substring(0, kmsKeyName.indexOf(cryptoKeyVersions));
```
Comment (frankyn) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java:632]: Update to, this is what we did in Python to prevent unintended behavior. 

```java
this.kmsKeyName = "";
```

Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java]: done

**Comment by athakor** [comment]
@frankyn PTAL

File: google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java [hunk 4]
```diff
@@ -621,7 +637,8 @@ Builder setCustomerEncryption(CustomerEncryption customerEncryption) {
 
     @Override
     Builder setKmsKeyName(String kmsKeyName) {
-      this.kmsKeyName = kmsKeyName;
+      this.kmsKeyName =
+          kmsKeyName != null && kmsKeyName.contains("cryptoKeyVersions") ? "" : kmsKeyName;
```
Comment (frankyn) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java:641]: This change should be in the HttpStorageRpc request being sent instead.

Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java]: done

**Review by frankyn — APPROVED** [review]
