### PR TITLE
fix: use %s instead of %d format specifier in checkArgument

### LINKED ISSUE #159: Using %d instead of %s for formating in checkArgument
There are currently being used %d instead of %s in template string to checkArguments in
https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L692

This makes the output from precondition failure come out awkwardly.

I guess someone with more routine in getting changes into this codebase can make this fix faster than me.

### PR DESCRIPTION
**Pull request by athakor**
Fixes #159

### CODE REVIEW

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 1]
```diff
@@ -689,7 +689,7 @@ public long read(
     Span span = startSpan(HttpStorageRpcSpans.SPAN_NAME_READ);
     Scope scope = tracer.withSpan(span);
     try {
-      checkArgument(position >= 0, "Position should be non-negative, is %d", position);
+      checkArgument(position >= 0, "Position should be non-negative, is %s", position);
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: I can't tell the difference between these two. %d looks correct to me. How about we use string concatenation with a plus sign here instead to avoid the issue.

I do notice this should probably not be inside the try block.

Comment (runevalle-cognite) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: %d had been correct with standard formater, but is incorrect when using guava's Precondition library formatting. (You can check documentation and code linked in the associated issue)

Comment (elharo) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: The mere fact that we have to check documentation and that this is not obvious strongly suggests that we shouldn't use a format string at all. Just use string concatenation and call it a day.

Comment (athakor) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: Done. I have used string concatenation `+` instead of `%s`. @elharo PTAL
