### PR TITLE
fix: connection closed prematurely in BlobReadChannel & ConnectionReset

### LINKED ISSUE #165: Tracking bug: com.google.cloud.storage.StorageException: Connection closed prematurely:..
Using a ReadChannel, if a premature connection closure occurs, the client isn't able to recover when it should be able to. The client at that moment has a specific range context which makes it retryable. 

Additionally, the implementation is too reliant on etag[1] not changing when generation number can do the same thing. This also needs to be addressed. 

Example failure:
```
CONFIG: -------------- REQUEST  --------------
GET http://localhost:8080/download/storage/v1/b/test-bucket/o/test-create-blob?alt=media
Accept-Encoding: gzip
Authorization: <Not Logged>
Range: bytes=0-10485759
User-Agent: gcloud-java/ Google-API-Java-Client/1.30.9 Google-HTTP-Java-Client/1.34.2 (gzip)
x-goog-api-client: gl-java/1.8.0 gdcl/1.30.9 linux/5.2.17
x-goog-testbench-instructions: return-broken-stream

Mar 06, 2020 8:47:01 AM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'Range: bytes=0-10485759' -H 'User-Agent: gcloud-java/ Google-API-Java-Client/1.30.9 Google-HTTP-Java-Client/1.34.2 (gzip)' -H 'x-goog-api-client: gl-java/1.8.0 gdcl/1.30.9 linux/5.2.17' -H 'x-goog-testbench-instructions: return-broken-stream' -- 'http://localhost:8080/download/storage/v1/b/test-bucket/o/test-create-blob?alt=media'
Mar 06, 2020 8:47:01 AM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.0 200 OK
Server: Werkzeug/1.0.0 Python/3.7.0
Content-Range: bytes 0-10485758/10485760
x-goog-generation: 1
Content-Length: 10485760
Date: Fri, 06 Mar 2020 16:47:01 GMT
Content-Type: text/html; charset=utf-8
x-goog-hash: md5=8clkXbwU793H2KMiaF8m6w==,crc32c=CPJwmw==

Mar 06, 2020 8:47:03 AM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG: Total: 1,114,112 bytes (logging first 16,384 bytes)
Mar 06, 2020 8:47:03 AM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 



com.google.cloud.storage.StorageException: Connection closed prematurely: bytesRead = 1114112, Content-Length = 10485760

	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:230)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:711)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:129)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:125)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.cloud.storage.it.ITStorageTest.testFailure(ITStorageTest.java:359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: Connection closed prematurely: bytesRead = 1114112, Content-Length = 10485760
	at com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.throwIfFalseEOF(NetHttpResponse.java:204)
	at com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.read(NetHttpResponse.java:166)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.google.api.client.util.LoggingInputStream.read(LoggingInputStream.java:57)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.api.client.util.ByteStreams.copy(ByteStreams.java:49)
	at com.google.api.client.util.IOUtils.copy(IOUtils.java:87)
	at com.google.api.client.util.IOUtils.copy(IOUtils.java:59)
	at com.google.api.client.http.HttpResponse.download(HttpResponse.java:410)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:706)
	... 40 more
```

Using C++ testbench[2] to reproduce issue but requires tweaks[3] to work with the Java library.

[1]: https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L133-L137
[2]: https://github.com/googleapis/google-cloud-cpp/tree/master/google/cloud/storage/testbench
[3]: https://github.com/googleapis/google-cloud-cpp/compare/master...frankyn:update-test-bench?expand=1

### PR DESCRIPTION
**Pull request by frankyn**
Fixes #165 

Introduce:

- `public StorageException(int code, String message, String reason, Throwable cause)`:
to capture the reason which is used to check RETRYABLE_ERRORS.
- `public static StorageException translate(IOException exception)`: to help translate idempotent request exceptions in case they're RETRYABLE_ERRORS. This translate method should be introduced for other idempotent requests, but that's out of scope for this request.

### CODE REVIEW

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 1]
```diff
@@ -704,6 +705,10 @@ public long read(
       StorageException serviceException = translate(ex);
       if (serviceException.getCode() == SC_REQUESTED_RANGE_NOT_SATISFIABLE) {
         return Tuple.of(null, new byte[0]);
+      } else if (serviceException.getMessage().contains("Connection closed prematurely")) {
+        serviceException = new StorageException(new SocketException(serviceException.getMessage()));
+      } else if (serviceException.getMessage().contains("Connection reset")) {
+        serviceException = new StorageException(new SocketException(serviceException.getMessage()));
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: This loses the stack trace; you should include the servieException too

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 2]
```diff
@@ -704,6 +705,10 @@ public long read(
       StorageException serviceException = translate(ex);
       if (serviceException.getCode() == SC_REQUESTED_RANGE_NOT_SATISFIABLE) {
         return Tuple.of(null, new byte[0]);
+      } else if (serviceException.getMessage().contains("Connection closed prematurely")) {
+        serviceException = new StorageException(new SocketException(serviceException.getMessage()));
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: This is very weird. I don't think I've ever seen this double wrapping in one throw clause done before. Can you explain the purpose here and how it works?

File: google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java [hunk 3]
```diff
@@ -84,6 +84,85 @@ public void testCreate() {
     assertTrue(reader.isOpen());
   }
 
+  @Test
+  public void testCreateRetryableErrorPrematureClosure() throws IOException {
+    byte[] arr = {0x0, 0xd, 0xa};
```
Comment (elharo) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java]: array (no abbreviations per Google style)

File: google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java [hunk 4]
```diff
@@ -84,6 +84,85 @@ public void testCreate() {
...
+    ByteBuffer byteBuffer = ByteBuffer.allocate(400);
+    expect(storageRpcMock.read(BLOB_ID.toPb(), EMPTY_RPC_OPTIONS, 0, 2097152)).andThrow(exception);
+    expect(storageRpcMock.read(BLOB_ID.toPb(), EMPTY_RPC_OPTIONS, 0, 2097152)).andReturn(test);
+    replay(storageRpcMock);
+    assertTrue(reader.read(byteBuffer) > 0);
+  }
+
+  @Test
+  public void testCreateNonRetryableErrorPrematureClosure() throws IOException {
+    byte[] arr = {0x0, 0xd, 0xa};
```
Comment (elharo) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java]: array

File: google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java [hunk 5]
```diff
@@ -84,6 +84,85 @@ public void testCreate() {
...
+    StorageException exception =
+        new StorageException(
+            new IOException(
+                "Connection closed prematurely: bytesRead = 1114112, Content-Length = 10485760"));
+    reader = new BlobReadChannel(options, BLOB_ID, EMPTY_RPC_OPTIONS);
+    ByteBuffer byteBuffer = ByteBuffer.allocate(400);
+    expect(storageRpcMock.read(BLOB_ID.toPb(), EMPTY_RPC_OPTIONS, 0, 2097152)).andThrow(exception);
+    replay(storageRpcMock);
+    try {
+      assertTrue(reader.read(byteBuffer) > 0);
```
Comment (elharo) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java]: don't both assertTrue and fail

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 6]
```diff
@@ -73,4 +82,16 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
     BaseServiceException.translate(ex);
     throw new StorageException(UNKNOWN_CODE, ex.getMessage(), ex.getCause());
   }
+
+  public static StorageException translate(IOException exception) {
```
Comment (crwilcox) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: Please add a comment for this.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 7]
```diff
@@ -226,6 +226,7 @@ public void onFailure(GoogleJsonError googleJsonError, HttpHeaders httpHeaders)
   }
 
   private static StorageException translate(IOException exception) {
+
```
Comment (crwilcox) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: Do we run a formatter for java? Is this blank line a problem for it?

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java (hunk 6 above)
Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: done

File: google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java (hunk 7 above)
Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: It doesn't clean it up surprisingly.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 8]
```diff
@@ -43,7 +46,9 @@
           new Error(500, null),
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: Where does this Error class come from?

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 9]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
     BaseServiceException.translate(ex);
     throw new StorageException(UNKNOWN_CODE, ex.getMessage(), ex.getCause());
   }
+
+  /**
+   * Translate IOException to the StorageException that caused the error. This method default to
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: defaults

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 10]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   * idempotent always being {@code True}. This method will force retry of the following transient
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: true? (primitive)
will force --> forces
or perhaps just will force retry of --> retries

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 11]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   * issues (Connection Closed Prematurely, Connection Reset).
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: "following" isn't needed; remove parentheses

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 12]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   *
+   * <p>Please Review {@code RETRYABLE_ERRORS} for a full list of retryable errors.
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: rewrite without "please Review"
also, never use Please in technical docs per https://developers.google.com/style/tone

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 13]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   *
+   * @throws StorageException when {@code ex} was caused by a {@code StorageException}
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: It returns, it doesn't throw

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java (hunk 8 above)
Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: https://github.com/googleapis/java-core/blob/master/google-cloud-core/src/main/java/com/google/cloud/BaseServiceException.java#L174

**Comment by frankyn** [comment]
Thanks @elharo, I addressed your comments.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java (hunk 8 above)
Comment (elharo) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: Also that's marked `@InternalApi` so it shouldn't be used here at all.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 14]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
     BaseServiceException.translate(ex);
     throw new StorageException(UNKNOWN_CODE, ex.getMessage(), ex.getCause());
   }
+
+  /**
+   * Translate IOException to the StorageException that caused the error. This method defaults to
+   * idempotent always being {@code true}. This method retries the transient issues Connection
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: I don't think it retries anything. There's no network connection here.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 15]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
     BaseServiceException.translate(ex);
     throw new StorageException(UNKNOWN_CODE, ex.getMessage(), ex.getCause());
   }
+
+  /**
+   * Translate IOException to the StorageException that caused the error. This method defaults to
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: to the... --> to a StorageException representing the cause of the error. (otherwise you have the effect coming before the cause.)

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 16]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   * idempotent always being {@code true}. This method retries the transient issues Connection
+   * Closed Prematurely and Connection Reset.
+   *
+   * <p>Review {@code RETRYABLE_ERRORS} for a full list of retryable errors.
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: RETRYABLE_ERRORS is rightly private, but it won't show in API docs.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java [hunk 17]
```diff
@@ -73,4 +82,25 @@ public static StorageException translateAndThrow(RetryHelperException ex) {
...
+   *
+   * @returns {@code StorageException}
+   */
+  public static StorageException translate(IOException exception) {
```
Comment (elharo) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: `translate` is an uncommon name for this operation. Perhaps `wrap`?

Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: Translate is what's being used in the code right now and wanted to keep consistent given there's already `translateAndThrow`

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java (hunk 14 above)
Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: Ah,,, that's not worded well fixing.

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java (hunk 8 above)
Comment (frankyn) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: StorageException is also annotated with `@InternalApi`. I'm not introducing the use Error(). I think this is okay, as Storage isn't the only library using the base class `BaseHttpServiceException`, e.g. [Bigquery](https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryException.java#L34).

Comment (chingor13) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: For `@InternalApi` from google-cloud-core, it's public because it needs to be, but intended for use by our libraries

Comment (elharo) [reply google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java]: I'll live with it this PR, but that's a major abuse of `@InternalApi`. It's as effectively locked in as any other public API. We should admit what's been done here, and remove `@InternalApi` from those classes. We can't change them absent an incompatible major version bump. :-(

**Comment by frankyn** [comment]
Merging after discussion with @elharo offline. Two approvals is more than enough for this.
